# Generated by Django 4.2.4 on 2023-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotumerakaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sur_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('recieved_by', models.CharField(max_length=50)),
            ],
        ),
    ]
