# Generated by Django 4.2.4 on 2023-09-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potumerakaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_name', models.CharField(max_length=150)),
                ('exp_incurred', models.IntegerField()),
            ],
        ),
    ]
